# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: order_service.proto for package 'ecommerce'

require 'grpc'
require 'order_service_pb'

module Ecommerce
  module OrderService
    # The OrderService definition.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'ecommerce.OrderService'

      # Creates a new order
      rpc :CreateOrder, ::Ecommerce::CreateOrderRequest, ::Ecommerce::OrderResponse
    end

    Stub = Service.rpc_stub_class
  end
end
