# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_service.proto

require 'google/protobuf'


descriptor_data = "\n\x15product_service.proto\x12\tecommerce\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"^\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\r\n\x05stock\x18\x05 \x01(\x05\x32U\n\x0eProductService\x12\x43\n\nGetProduct\x12\x19.ecommerce.ProductRequest\x1a\x1a.ecommerce.ProductResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Ecommerce
  ProductRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ecommerce.ProductRequest").msgclass
  ProductResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ecommerce.ProductResponse").msgclass
end

module ProductServicePb
end

module ProductServiceServicesPb
end
